# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b62d3887e9fd0592bbdd077071c28061"
name = "llms-generator"
handle = "llms-generator"
application_url = "https://fact-course-tribune-firewire.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://fact-course-tribune-firewire.trycloudflare.com/auth/callback",
  "https://fact-course-tribune-firewire.trycloudflare.com/auth/shopify/callback",
  "https://fact-course-tribune-firewire.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
